AllCops:
  Include:
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/*.rb'
    - '**/config.ru'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
    - '**/Fastfile'
    - '**/*Fastfile'
  Exclude:
    - '**/*.gemspec'
    - '**/Gemfile*'
    - 'Gemfile*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*.rb'
    - 'config/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'var/**/*'
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'infra/**/*'
    - 'db/**/*'
    - Guardfile
